"""Formal statistical evaluation of the corrected WSC v2 campaign vs. the
frozen Original (non-WSC) 12-seed formal experiment.

EVALUATION-ONLY. Does not launch, resume, or modify any training. Does not
touch any scientific training code, reward/GGI/lambda definitions, WSC
feature definitions, checkpoint expansion, or checkpoints (v1 invalid, v2
formal, or Original).

Statistical protocol reused verbatim from the project's own canonical
formal-analysis script (cited functions copied byte-for-byte, not
reinvented):
    F:\\正式训练_seed_replication_v1\\analysis_scripts\\pooled12\\merge_and_audit.py
    -- gini(), bootstrap_ci_paired(), bootstrap_p_value(), holm_correction()
This establishes (from that script's own Task 1/Task 4 usage):
    - resampling unit           : SEED (paired bootstrap over 12 seed-level means)
    - n_boot                    : 10,000
    - bootstrap rng_seed        : 0 (np.random.default_rng(0))
    - CI type                   : percentile bootstrap, [2.5, 97.5] -> 95% CI
    - p-value                   : two-sided, p = min(1, 2*min(P(boot<=0), P(boot>=0)))
    - Holm family (established) : within ONE outcome, across the non-reference
                                   condition comparisons (Task 4 did this for
                                   U_min across {GGI-Mean, Maximin-Mean}, m=2).
This script's extension of that convention (documented, not invented after
seeing results): for the WSC interaction analysis, the natural non-reference
comparison set per outcome is the three welfare conditions {Mean, GGI,
Maximin} (each vs. its own Baseline, via the interaction term) -> TWO
independent Holm families of m=3 each: (1) U_min interaction family, (2)
Utility Gini interaction family. These are NOT pooled into one m=6 family,
consistent with the project's practice of keeping each outcome as its own
correction family.

Data sources (all pre-existing, none regenerated by this script unless
explicitly noted):
    Original Baseline : F:\\正式训练\\outputs\\welfare_analysis\\taskonly_evaluation_merged.csv
    Original Mean/GGI/Maximin : F:\\正式训练_seed_replication_v1\\analysis_scripts\\pooled12\\outputs\\pooled12_welfare_evaluation_merged.csv
    WSC v2 (corrected) all 4 conditions : F:\\正式训练_seed_replication_v1\\analysis_scripts\\ch5_baseline\\outputs\\wsc_interim_v2\\wsc_interim_v2_evaluation_all12.csv
        (generated by evaluate_wsc_formal_v2.py: include_welfare_state=True,
        obs_dim=22, corrected wsc_checkpoint_expansion, H1 bank, 256
        scenarios/seed-condition, greedy epsilon=0, 4-checkpoint ensemble
        {1,850,000; 1,900,000; 1,950,000; 2,000,000}, sourced from
        checkpoints/wsc_formal_runs_v2/ only. This IS the formal WSC
        evaluator per the task spec in section 5; not re-run here since it
        already satisfies every stated requirement.)

Run: python wsc_v2_formal_analysis.py
"""
from __future__ import annotations
import os

import csv
import hashlib
import json
import math
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------- CONFIG
SEEDS_12 = [900101, 900102, 900103, 900104, 910101, 910102,
            920101, 920102, 920103, 920104, 920105, 920106]
SENSITIVITY_EXCLUDE_SEED = 910102
CONDITIONS = ["baseline", "mean", "ggi", "maximin"]
WELFARE_CONDITIONS = ["mean", "ggi", "maximin"]  # non-reference, vs. Baseline
BANK = "H1"
N_EPISODES_EXPECTED = 256
N_BOOT = 10000
BOOT_RNG_SEED = 0
ALPHA = 0.05

REPO_ROOT = Path(os.environ.get("SEED_REPL_BUNDLE", ""))  # raw checkpoints not distributed with this repo; set env var
ORIGINAL_BASELINE_CSV = Path(__file__).resolve().parent.parent / "data" / "taskonly_evaluation_merged.csv"
ORIGINAL_WELFARE_CSV = REPO_ROOT / "analysis_scripts" / "pooled12" / "outputs" / "pooled12_welfare_evaluation_merged.csv"
WSC_V2_CSV = REPO_ROOT / "analysis_scripts" / "ch5_baseline" / "outputs" / "wsc_interim_v2" / "wsc_interim_v2_evaluation_all12.csv"
WSC_V2_REGISTRY = Path(os.environ.get("SEED_REPL_BUNDLE", "")) / "validation_artifacts" / "wsc_formal_launch_v2" / "wsc_formal_run_registry_v2.csv"  # not distributed with this repo
V1_INVALID_REGISTRY = Path(os.environ.get("SEED_REPL_BUNDLE", "")) / "validation_artifacts" / "wsc_formal_launch" / "wsc_formal_run_registry.csv"  # not distributed with this repo
FREEZE_MANIFEST_V2 = REPO_ROOT / "validation_artifacts" / "wsc_formal_launch_v2" / "wsc_scientific_freeze_manifest_v2.json"

OUT_DIR = Path(__file__).resolve().parent / "outputs"
OUT_DIR.mkdir(parents=True, exist_ok=True)

ENSEMBLE_WINDOW = [1850000, 1900000, 1950000, 2000000]
WSC_OUTPUT_ROOT = Path(os.environ.get("SEED_REPL_BUNDLE", "")) / "checkpoints" / "wsc_formal_runs_v2"  # not distributed with this repo
INVALID_V1_ROOT = Path(os.environ.get("SEED_REPL_BUNDLE", "")) / "checkpoints" / "wsc_formal_runs"  # not distributed with this repo

LOG: list[str] = []


def log(msg: str = "") -> None:
    print(msg)
    LOG.append(msg)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ============================================================================
# Reused verbatim from pooled12/merge_and_audit.py (cited above) -- the
# project's own canonical statistical machinery. Not reimplemented.
# ============================================================================
def gini(values):
    n = len(values)
    total = sum(values)
    if total == 0:
        return None
    numerator = sum(abs(a - b) for a in values for b in values)
    return float(numerator / (2.0 * n * total))


def bootstrap_ci_paired(diffs: np.ndarray, n_boot: int = N_BOOT, rng_seed: int = BOOT_RNG_SEED):
    rng = np.random.default_rng(rng_seed)
    n = len(diffs)
    boot = np.empty(n_boot)
    for i in range(n_boot):
        idx = rng.integers(0, n, n)
        boot[i] = np.mean(diffs[idx])
    return float(np.mean(diffs)), float(np.percentile(boot, 2.5)), float(np.percentile(boot, 97.5)), boot


def bootstrap_p_value(boot_diffs: np.ndarray) -> float:
    p_le = float(np.mean(boot_diffs <= 0))
    p_ge = float(np.mean(boot_diffs >= 0))
    return float(min(1.0, 2.0 * min(p_le, p_ge)))


def holm_correction(pvals: list[float]) -> list[float]:
    m = len(pvals)
    order = sorted(range(m), key=lambda i: pvals[i])
    adjusted = [0.0] * m
    running_max = 0.0
    for rank, i in enumerate(order):
        adj = (m - rank) * pvals[i]
        running_max = max(running_max, adj)
        adjusted[i] = min(1.0, running_max)
    return adjusted


# ============================================================================
# Section 4/12: WSC v2 run validity + technical-health audit
# ============================================================================
def audit_wsc_v2_runs() -> dict:
    with open(WSC_V2_REGISTRY, encoding="utf-8") as f:
        reg = list(csv.DictReader(f))
    assert len(reg) == 48, f"expected 48 WSC v2 registry rows, got {len(reg)}"

    problems = []
    checked = 0
    for r in reg:
        seed, cond, run_id = r["seed"], r["condition"], r["run_id"]
        if r["status"] != "COMPLETED" or r["exit_code"] != "0":
            problems.append(f"{run_id}: status={r['status']} exit_code={r['exit_code']}")
            continue
        src = r["source_checkpoint"]
        if "wsc" in src.lower() or str(INVALID_V1_ROOT) in src:
            problems.append(f"{run_id}: source checkpoint looks WSC-derived or pre-fix invalid: {src}")
        if "ckpt_step_1200000.pt" not in src:
            problems.append(f"{run_id}: source checkpoint is not step 1,200,000: {src}")
        out_dir = Path(r["output_dir"])
        if WSC_OUTPUT_ROOT.name not in str(out_dir) or str(INVALID_V1_ROOT) == str(out_dir.parent):
            problems.append(f"{run_id}: output_dir does not look like the v2 root: {out_dir}")
        stage = f"Formal_{cond}_WSC_v2"
        ckpt_dir = out_dir / f"seed_{seed}_{stage}"
        for step in ENSEMBLE_WINDOW:
            if not (ckpt_dir / f"ckpt_step_{step}.pt").exists():
                problems.append(f"{run_id}: missing ensemble checkpoint step {step}")
        checked += 1

    with open(V1_INVALID_REGISTRY, encoding="utf-8") as f:
        v1_reg = list(csv.DictReader(f))
    n_invalid_marked = sum(1 for r in v1_reg if r["status"] == "INVALID_PRE_FIX_COLUMN_MAPPING")

    result = {
        "n_v2_registry_rows": len(reg),
        "n_v2_checked_ok": checked,
        "n_v2_problems": len(problems),
        "problems": problems,
        "n_v1_invalid_registry_rows": len(v1_reg),
        "n_v1_marked_invalid": n_invalid_marked,
        "v1_isolation_ok": n_invalid_marked == 48 and len(v1_reg) == 48,
    }
    return result


# ============================================================================
# Data loading
# ============================================================================
def _safe_float(x, default=0.0):
    return float(x) if x not in (None, "") else default


def _seed_level_from_rows(rows: list[dict], seed: int, bank: str = BANK) -> dict:
    sub = [r for r in rows if int(r["seed"]) == seed and r["bank"] == bank]
    if len(sub) != N_EPISODES_EXPECTED:
        raise ValueError(f"seed {seed}: expected {N_EPISODES_EXPECTED} episodes, got {len(sub)}")
    completion = [float(r["completion"]) for r in sub]
    collision = [float(r["collision"]) for r in sub]
    umin = [float(r["min_U"]) for r in sub]
    ginis = [_safe_float(r["gini"], 0.0) for r in sub]  # gini undefined (empty) only when all-4-utilities==0; treat as 0 (perfectly equal, all-zero)
    for name, vals in (("completion", completion), ("collision", collision), ("min_U", umin), ("gini", ginis)):
        if not all(math.isfinite(v) for v in vals):
            raise ValueError(f"seed {seed}: non-finite value(s) in {name}")
    return {
        "completion": float(np.mean(completion)),
        "collision": float(np.mean(collision)),
        "U_min": float(np.mean(umin)),
        "gini": float(np.mean(ginis)),
    }


def load_original() -> dict:
    with open(ORIGINAL_BASELINE_CSV, encoding="utf-8") as f:
        baseline_rows = list(csv.DictReader(f))
    with open(ORIGINAL_WELFARE_CSV, encoding="utf-8") as f:
        welfare_rows = list(csv.DictReader(f))

    out = {cond: {} for cond in CONDITIONS}
    for seed in SEEDS_12:
        out["baseline"][seed] = _seed_level_from_rows(
            [r for r in baseline_rows if r["condition"] == "taskonly"], seed
        )
        for cond in WELFARE_CONDITIONS:
            out[cond][seed] = _seed_level_from_rows(
                [r for r in welfare_rows if r["condition"] == cond], seed
            )
    return out


def load_wsc() -> dict:
    with open(WSC_V2_CSV, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    out = {cond: {} for cond in CONDITIONS}
    seen = set()
    for cond in CONDITIONS:
        cond_rows = [r for r in rows if r["condition"] == cond]
        for seed in SEEDS_12:
            key = (cond, seed)
            if key in seen:
                raise ValueError(f"duplicate seed-condition row detected: {key}")
            seen.add(key)
            out[cond][seed] = _seed_level_from_rows(cond_rows, seed)
    if len(seen) != len(CONDITIONS) * len(SEEDS_12):
        raise ValueError("did not find exactly 12 seeds x 4 conditions in WSC v2 CSV")
    return out


# ============================================================================
# Seed-level table (Section 8 / output 1)
# ============================================================================
def build_seed_level_table(orig: dict, wsc: dict) -> list[dict]:
    rows = []
    for seed in SEEDS_12:
        for cond in CONDITIONS:
            o = orig[cond][seed]
            w = wsc[cond][seed]
            row = {
                "seed": seed, "condition": cond,
                "orig_completion": o["completion"], "orig_collision": o["collision"],
                "orig_U_min": o["U_min"], "orig_gini": o["gini"],
                "wsc_completion": w["completion"], "wsc_collision": w["collision"],
                "wsc_U_min": w["U_min"], "wsc_gini": w["gini"],
                "delta_completion_wsc_minus_orig": w["completion"] - o["completion"],
                "delta_collision_wsc_minus_orig": w["collision"] - o["collision"],
            }
            if cond in WELFARE_CONDITIONS:
                bo = orig["baseline"][seed]
                bw = wsc["baseline"][seed]
                orig_contrast_umin = o["U_min"] - bo["U_min"]
                wsc_contrast_umin = w["U_min"] - bw["U_min"]
                orig_contrast_gini = o["gini"] - bo["gini"]
                wsc_contrast_gini = w["gini"] - bw["gini"]
                row.update({
                    "orig_contrast_Umin_vs_baseline": orig_contrast_umin,
                    "wsc_contrast_Umin_vs_baseline": wsc_contrast_umin,
                    "I_Umin": wsc_contrast_umin - orig_contrast_umin,
                    "orig_contrast_gini_vs_baseline": orig_contrast_gini,
                    "wsc_contrast_gini_vs_baseline": wsc_contrast_gini,
                    "I_Gini": wsc_contrast_gini - orig_contrast_gini,
                })
            rows.append(row)
    return rows


# ============================================================================
# Fairness interaction formal analysis (Section 7)
# ============================================================================
def fairness_analysis(seed_level_rows: list[dict], seed_set: list[int], label: str) -> dict:
    n = len(seed_set)
    result = {"n": n, "seed_set": seed_set, "label": label, "outcomes": {}}
    for outcome, key in (("U_min", "I_Umin"), ("Gini", "I_Gini")):
        raw_p = {}
        est_ci = {}
        per_cond_vals = {}
        for cond in WELFARE_CONDITIONS:
            vals = np.array([
                r[key] for r in seed_level_rows
                if r["condition"] == cond and r["seed"] in seed_set
            ])
            assert len(vals) == n, (outcome, cond, len(vals), n)
            est, lo, hi, boot = bootstrap_ci_paired(vals, n_boot=N_BOOT, rng_seed=BOOT_RNG_SEED)
            p = bootstrap_p_value(boot)
            raw_p[cond] = p
            est_ci[cond] = (est, lo, hi)
            per_cond_vals[cond] = vals.tolist()
        order = WELFARE_CONDITIONS  # fixed order: mean, ggi, maximin (m=3 Holm family)
        pvals = [raw_p[c] for c in order]
        adj = holm_correction(pvals)
        outcome_result = {}
        for cond, p, a in zip(order, pvals, adj):
            est, lo, hi = est_ci[cond]
            vals = np.array(per_cond_vals[cond])
            outcome_result[cond] = {
                "n": n, "mean": est, "median": float(np.median(vals)), "sd": float(np.std(vals, ddof=1)),
                "n_positive": int(np.sum(vals > 0)), "n_negative": int(np.sum(vals < 0)), "n_zero": int(np.sum(vals == 0)),
                "CI95_low": lo, "CI95_high": hi, "raw_p_bootstrap_two_sided": p,
                "holm_adjusted_p": a, "reject_at_alpha05": bool(a < ALPHA),
                "seed_values": {int(s): float(v) for s, v in zip(seed_set, vals)},
            }
        result["outcomes"][outcome] = outcome_result
    return result


def leave_one_seed_out(seed_level_rows: list[dict]) -> list[dict]:
    rows = []
    for outcome, key in (("U_min", "I_Umin"), ("Gini", "I_Gini")):
        for cond in WELFARE_CONDITIONS:
            full_vals = {r["seed"]: r[key] for r in seed_level_rows if r["condition"] == cond}
            full_est = float(np.mean(list(full_vals.values())))
            loo_ests = {}
            for excl in SEEDS_12:
                remaining = [v for s, v in full_vals.items() if s != excl]
                loo_ests[excl] = float(np.mean(remaining))
            shifts = {s: loo_ests[s] - full_est for s in SEEDS_12}
            max_shift_seed = max(shifts, key=lambda s: abs(shifts[s]))
            for seed in SEEDS_12:
                rows.append({
                    "outcome": outcome, "condition": cond, "excluded_seed": seed,
                    "leave_one_out_estimate": loo_ests[seed],
                    "full_n12_estimate": full_est,
                    "shift_from_full": shifts[seed],
                    "is_largest_shift_seed": seed == max_shift_seed,
                })
    return rows


# ============================================================================
# Safety analysis (Section 10) -- descriptive, paired bootstrap, NOT Holm-corrected
# (no established formal family for this exact comparison in the project's
# prior protocol -- see module docstring / report Section C for rationale)
# ============================================================================
def safety_analysis(seed_level_rows: list[dict]) -> dict:
    result = {}
    for metric, key in (("completion", "delta_completion_wsc_minus_orig"), ("collision", "delta_collision_wsc_minus_orig")):
        result[metric] = {}
        for cond in CONDITIONS:
            vals = np.array([r[key] for r in seed_level_rows if r["condition"] == cond])
            assert len(vals) == 12
            est, lo, hi, boot = bootstrap_ci_paired(vals, n_boot=N_BOOT, rng_seed=BOOT_RNG_SEED)
            p = bootstrap_p_value(boot)
            result[metric][cond] = {
                "n": 12, "mean_paired_diff": est, "median_paired_diff": float(np.median(vals)),
                "sd": float(np.std(vals, ddof=1)), "n_positive": int(np.sum(vals > 0)),
                "n_negative": int(np.sum(vals < 0)), "n_zero": int(np.sum(vals == 0)),
                "CI95_low": lo, "CI95_high": hi, "raw_p_bootstrap_two_sided": p,
                "note": "descriptive/safety -- not part of a pre-specified Holm-corrected confirmatory family",
                "seed_values": {int(r["seed"]): float(r[key]) for r in seed_level_rows if r["condition"] == cond},
            }
    return result


def heterogeneity_metrics(seed_level_rows: list[dict]) -> dict:
    out = {}
    for metric, key in (("delta_completion", "delta_completion_wsc_minus_orig"), ("delta_collision", "delta_collision_wsc_minus_orig")):
        out[metric] = {}
        for cond in CONDITIONS:
            vals = np.array([r[key] for r in seed_level_rows if r["condition"] == cond])
            q1, q3 = np.percentile(vals, [25, 75])
            out[metric][cond] = {
                "sd": float(np.std(vals, ddof=1)), "min": float(np.min(vals)), "max": float(np.max(vals)),
                "iqr": float(q3 - q1), "n_positive": int(np.sum(vals > 0)), "n_negative": int(np.sum(vals < 0)),
            }
    for outcome, key in (("I_Umin", "I_Umin"), ("I_Gini", "I_Gini")):
        out[outcome] = {}
        for cond in WELFARE_CONDITIONS:
            vals = np.array([r[key] for r in seed_level_rows if r["condition"] == cond])
            q1, q3 = np.percentile(vals, [25, 75])
            out[outcome][cond] = {
                "sd": float(np.std(vals, ddof=1)), "min": float(np.min(vals)), "max": float(np.max(vals)),
                "iqr": float(q3 - q1), "n_positive": int(np.sum(vals > 0)), "n_negative": int(np.sum(vals < 0)),
            }
    return out


# ============================================================================
# Provenance
# ============================================================================
def build_provenance(run_audit: dict) -> dict:
    prov = {
        "analysis_script": str(Path(__file__).resolve()),
        "inputs": {
            "original_baseline_csv": {"path": str(ORIGINAL_BASELINE_CSV), "sha256": sha256_file(ORIGINAL_BASELINE_CSV)},
            "original_welfare_csv": {"path": str(ORIGINAL_WELFARE_CSV), "sha256": sha256_file(ORIGINAL_WELFARE_CSV)},
            "wsc_v2_evaluation_csv": {"path": str(WSC_V2_CSV), "sha256": sha256_file(WSC_V2_CSV)},
            "wsc_v2_registry": {"path": str(WSC_V2_REGISTRY), "sha256": sha256_file(WSC_V2_REGISTRY)},
            "v1_invalid_registry": {"path": str(V1_INVALID_REGISTRY), "sha256": sha256_file(V1_INVALID_REGISTRY)},
            "freeze_manifest_v2": {"path": str(FREEZE_MANIFEST_V2), "sha256": sha256_file(FREEZE_MANIFEST_V2)},
        },
        "wsc_v2_run_audit": run_audit,
        "seeds_12": SEEDS_12,
        "sensitivity_excluded_seed": SENSITIVITY_EXCLUDE_SEED,
        "bank": BANK,
        "n_episodes_per_seed_condition": N_EPISODES_EXPECTED,
        "ensemble_window": ENSEMBLE_WINDOW,
        "bootstrap": {"n_boot": N_BOOT, "rng_seed": BOOT_RNG_SEED, "ci": "percentile [2.5, 97.5]",
                      "p_value": "two-sided, min(1, 2*min(P(boot<=0), P(boot>=0)))",
                      "resampling_unit": "seed (paired bootstrap over seed-level interaction/contrast values)",
                      "source_of_protocol": str(Path(r"F:\正式训练_seed_replication_v1\analysis_scripts\pooled12\merge_and_audit.py"))},
        "holm_family_definition": {
            "U_min_interaction_family": WELFARE_CONDITIONS,
            "Gini_interaction_family": WELFARE_CONDITIONS,
            "note": "two independent m=3 families, one per outcome; NOT pooled into one m=6 family; "
                    "safety (completion/collision) comparisons are descriptive, not Holm-corrected "
                    "(no established formal family for this exact comparison existed in the project's prior protocol).",
        },
    }
    return prov


def main() -> int:
    log("=" * 78)
    log("WSC v2 FORMAL EVALUATION -- evaluation-only, no training changes")
    log("=" * 78)
    log(f"Original baseline CSV : {ORIGINAL_BASELINE_CSV}")
    log(f"Original welfare CSV  : {ORIGINAL_WELFARE_CSV}")
    log(f"WSC v2 evaluation CSV : {WSC_V2_CSV}")
    log(f"seeds (n=12)          : {SEEDS_12}")
    log(f"bootstrap             : n_boot={N_BOOT} rng_seed={BOOT_RNG_SEED} CI=percentile[2.5,97.5] two-sided p")

    run_audit = audit_wsc_v2_runs()
    log(f"\nWSC v2 run audit: {run_audit['n_v2_checked_ok']}/{run_audit['n_v2_registry_rows']} rows OK, "
        f"{run_audit['n_v2_problems']} problems")
    if run_audit["n_v2_problems"] > 0:
        for p in run_audit["problems"]:
            log(f"  PROBLEM: {p}")
        raise SystemExit("FATAL: WSC v2 run audit found problems -- refusing to proceed with formal analysis.")
    if not run_audit["v1_isolation_ok"]:
        raise SystemExit("FATAL: v1 invalid registry isolation check failed.")
    log("v1 invalid registry isolation: OK (48/48 rows marked INVALID_PRE_FIX_COLUMN_MAPPING, untouched)")

    orig = load_original()
    wsc = load_wsc()
    seed_level_rows = build_seed_level_table(orig, wsc)

    # reproducibility guards
    assert len(seed_level_rows) == len(SEEDS_12) * len(CONDITIONS)
    seen_keys = set()
    for r in seed_level_rows:
        key = (r["seed"], r["condition"])
        if key in seen_keys:
            raise ValueError(f"duplicate seed-condition row in seed-level table: {key}")
        seen_keys.add(key)
    for r in seed_level_rows:
        for k, v in r.items():
            if isinstance(v, float) and not math.isfinite(v):
                raise ValueError(f"non-finite value in seed-level row {r['seed']}/{r['condition']}: {k}={v}")

    seed_level_csv = OUT_DIR / "wsc_v2_formal_seed_level.csv"
    fieldnames: list[str] = []
    for r in seed_level_rows:
        for k in r.keys():
            if k not in fieldnames:
                fieldnames.append(k)
    for r in seed_level_rows:
        for k in fieldnames:
            r.setdefault(k, "")
    with open(seed_level_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(seed_level_rows)
    log(f"\nwrote {seed_level_csv}  ({len(seed_level_rows)} rows)")

    # --- Primary n=12 fairness analysis ---
    primary = fairness_analysis(seed_level_rows, SEEDS_12, "primary_n12")
    sens_seeds = [s for s in SEEDS_12 if s != SENSITIVITY_EXCLUDE_SEED]
    sensitivity = fairness_analysis(seed_level_rows, sens_seeds, "sensitivity_n11_excl_910102")

    log("\n" + "=" * 78)
    log("PRIMARY (n=12) fairness interaction results")
    log("=" * 78)
    for outcome in ("U_min", "Gini"):
        log(f"\n--- {outcome} interaction ---")
        for cond in WELFARE_CONDITIONS:
            d = primary["outcomes"][outcome][cond]
            log(f"  {cond.upper():8} mean={d['mean']:+.4f} median={d['median']:+.4f} sd={d['sd']:.4f} "
                f"pos/neg/zero={d['n_positive']}/{d['n_negative']}/{d['n_zero']} "
                f"CI95=[{d['CI95_low']:+.4f},{d['CI95_high']:+.4f}] raw_p={d['raw_p_bootstrap_two_sided']:.4f} "
                f"holm_p={d['holm_adjusted_p']:.4f} reject={d['reject_at_alpha05']}")

    log("\n" + "=" * 78)
    log("SENSITIVITY (n=11, excl. seed 910102) fairness interaction results")
    log("=" * 78)
    for outcome in ("U_min", "Gini"):
        log(f"\n--- {outcome} interaction ---")
        for cond in WELFARE_CONDITIONS:
            d = sensitivity["outcomes"][outcome][cond]
            log(f"  {cond.upper():8} mean={d['mean']:+.4f} CI95=[{d['CI95_low']:+.4f},{d['CI95_high']:+.4f}] "
                f"holm_p={d['holm_adjusted_p']:.4f} reject={d['reject_at_alpha05']}")

    # fairness summary CSV
    fairness_summary_rows = []
    for label, res in (("primary_n12", primary), ("sensitivity_n11_excl_910102", sensitivity)):
        for outcome in ("U_min", "Gini"):
            for cond in WELFARE_CONDITIONS:
                d = res["outcomes"][outcome][cond]
                fairness_summary_rows.append({
                    "analysis": label, "outcome": outcome, "condition": cond, "n": d["n"],
                    "mean": round(d["mean"], 6), "median": round(d["median"], 6), "sd": round(d["sd"], 6),
                    "n_positive": d["n_positive"], "n_negative": d["n_negative"], "n_zero": d["n_zero"],
                    "CI95_low": round(d["CI95_low"], 6), "CI95_high": round(d["CI95_high"], 6),
                    "raw_p_bootstrap": round(d["raw_p_bootstrap_two_sided"], 6),
                    "holm_adjusted_p": round(d["holm_adjusted_p"], 6),
                    "reject_at_alpha05": d["reject_at_alpha05"],
                })
    fairness_csv = OUT_DIR / "wsc_v2_formal_fairness_summary.csv"
    with open(fairness_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(fairness_summary_rows[0].keys()))
        w.writeheader(); w.writerows(fairness_summary_rows)
    log(f"\nwrote {fairness_csv}")

    # sensitivity side-by-side CSV
    sens_rows = []
    for outcome in ("U_min", "Gini"):
        for cond in WELFARE_CONDITIONS:
            p12 = primary["outcomes"][outcome][cond]
            p11 = sensitivity["outcomes"][outcome][cond]
            qual_p12 = "positive" if p12["mean"] > 0 else ("negative" if p12["mean"] < 0 else "zero")
            qual_p11 = "positive" if p11["mean"] > 0 else ("negative" if p11["mean"] < 0 else "zero")
            sens_rows.append({
                "outcome": outcome, "condition": cond,
                "n12_mean": round(p12["mean"], 6), "n12_CI_low": round(p12["CI95_low"], 6), "n12_CI_high": round(p12["CI95_high"], 6),
                "n11_mean": round(p11["mean"], 6), "n11_CI_low": round(p11["CI95_low"], 6), "n11_CI_high": round(p11["CI95_high"], 6),
                "point_estimate_change": round(p11["mean"] - p12["mean"], 6),
                "qualitative_direction_n12": qual_p12, "qualitative_direction_n11": qual_p11,
                "direction_changed": qual_p12 != qual_p11,
            })
    sens_csv = OUT_DIR / "wsc_v2_formal_sensitivity_910102.csv"
    with open(sens_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(sens_rows[0].keys()))
        w.writeheader(); w.writerows(sens_rows)
    log(f"wrote {sens_csv}")

    # leave-one-out
    loo_rows = leave_one_seed_out(seed_level_rows)
    loo_csv = OUT_DIR / "wsc_v2_leave_one_seed_out.csv"
    with open(loo_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(loo_rows[0].keys()))
        w.writeheader(); w.writerows(loo_rows)
    log(f"wrote {loo_csv}")

    # safety analysis
    safety = safety_analysis(seed_level_rows)
    log("\n" + "=" * 78)
    log("SAFETY / TASK-PERFORMANCE analysis (descriptive, paired, n=12)")
    log("=" * 78)
    safety_rows = []
    for metric in ("completion", "collision"):
        for cond in CONDITIONS:
            d = safety[metric][cond]
            log(f"  Delta_{metric:10} {cond:8} mean={d['mean_paired_diff']:+.4f} CI95=[{d['CI95_low']:+.4f},{d['CI95_high']:+.4f}] "
                f"pos/neg={d['n_positive']}/{d['n_negative']} raw_p={d['raw_p_bootstrap_two_sided']:.4f}")
            safety_rows.append({
                "metric": metric, "condition": cond, "n": d["n"],
                "mean_paired_diff_wsc_minus_orig": round(d["mean_paired_diff"], 6),
                "median_paired_diff": round(d["median_paired_diff"], 6), "sd": round(d["sd"], 6),
                "n_positive": d["n_positive"], "n_negative": d["n_negative"], "n_zero": d["n_zero"],
                "CI95_low": round(d["CI95_low"], 6), "CI95_high": round(d["CI95_high"], 6),
                "raw_p_bootstrap_two_sided": round(d["raw_p_bootstrap_two_sided"], 6),
                "note": d["note"],
            })
    safety_csv = OUT_DIR / "wsc_v2_formal_safety_summary.csv"
    with open(safety_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(safety_rows[0].keys()))
        w.writeheader(); w.writerows(safety_rows)
    log(f"\nwrote {safety_csv}")

    heterogeneity = heterogeneity_metrics(seed_level_rows)

    provenance = build_provenance(run_audit)
    prov_path = OUT_DIR / "wsc_v2_data_provenance.json"
    with open(prov_path, "w", encoding="utf-8") as f:
        json.dump(provenance, f, indent=2, default=str)
    log(f"wrote {prov_path}")

    bootstrap_results = {
        "config": {
            "seeds_12": SEEDS_12, "sensitivity_excluded_seed": SENSITIVITY_EXCLUDE_SEED,
            "n_boot": N_BOOT, "rng_seed": BOOT_RNG_SEED, "alpha": ALPHA,
            "welfare_conditions": WELFARE_CONDITIONS, "bank": BANK,
        },
        "primary_n12": primary,
        "sensitivity_n11": sensitivity,
        "safety": safety,
        "heterogeneity": heterogeneity,
        "run_audit": run_audit,
    }
    boot_json_path = OUT_DIR / "wsc_v2_formal_bootstrap_results.json"
    with open(boot_json_path, "w", encoding="utf-8") as f:
        json.dump(bootstrap_results, f, indent=2, default=str)
    log(f"wrote {boot_json_path}")

    with open(OUT_DIR / "wsc_v2_formal_analysis_log.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(LOG))

    log("\nDONE.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
